test:
  adapter: mysql2
  database: mygem_test
  username: foobar
  encoding: utf8

test_mysql:
  adapter: mysql2
  database: mygem_test
  username: root
  encoding: utf8
  
test_postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

test_sqlserver:
  adapter: sqlserver
  database: guest
  username: 
  password: 
  host: localhost
  encoding: utf8
